import argparse
import datetime

import yaml
from rosdistro import (
    DistributionCache,
    get_cached_distribution,
    get_distribution_cache_string,
    get_index,
    get_index_url,
)
from rosdistro.loader import load_url

from .distro import Distro

ROSDISTRO_RAW_URL = "https://raw.githubusercontent.com/ros/rosdistro"


def load_distribution_cache(distro_name, rosdistro_ref=None):
    """The rosdistro distribution cache, optionally for a git ref of ros/rosdistro.

    The published cache (repo.ros2.org) always follows rosdistro's default branch.
    With a ref, e.g. a sync tag such as ``jazzy/2026-10-05``, the distribution file
    of that ref replaces the cached one: package.xml entries whose release changed
    are dropped and fetched again for the version of the ref, everything else is
    reused from the published cache.
    """
    cache_yaml = get_distribution_cache_string(get_index(get_index_url()), distro_name)
    cache = DistributionCache(distro_name, yaml.safe_load(cache_yaml))
    if not rosdistro_ref:
        return cache

    index = get_index(f"{ROSDISTRO_RAW_URL}/{rosdistro_ref}/index-v4.yaml")
    urls = index.distributions[distro_name]["distribution"]
    urls = urls if isinstance(urls, list) else [urls]
    data = [yaml.safe_load(load_url(url)) for url in urls]
    cache.update_distribution(data)

    # fetch the package.xml files the update dropped (only changed releases)
    dist = get_cached_distribution(
        index, distro_name, cache=cache, allow_lazy_load=True
    )
    for pkg_name in sorted(dist.release_packages):
        if pkg_name not in cache.release_package_xmls:
            dist.get_release_package_xml(pkg_name)
    return cache


def main():
    parser = argparse.ArgumentParser(
        description="Dependency snapshotting tool for ROS packages"
    )
    parser.add_argument(
        "-d",
        "--distro",
        type=str,
        dest="distro",
        default="humble",
        help="ROS distribution to use (default: humble)",
        required=False,
    )
    parser.add_argument(
        "-p",
        "--package",
        type=str,
        dest="package",
        default=None,
        help="ROS package to get dependencies for (default: ALL)",
        required=False,
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        dest="output",
        default="rosdistro_snapshot.yaml",
        help="Output file to write dependencies to",
        required=False,
    )
    parser.add_argument(
        "--rosdistro-ref",
        type=str,
        dest="rosdistro_ref",
        default=None,
        help="git ref of ros/rosdistro to snapshot, e.g. a sync tag such as "
        "'jazzy/2026-10-05' (default: the published cache, i.e. the latest state)",
        required=False,
    )
    parser.add_argument(
        "-q",
        "--quiet",
        dest="quiet",
        action="store_true",
        help="Suppress output to stdout",
        required=False,
    )
    args = parser.parse_args()

    # Get the current UTC time
    utc_time = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    # Fetch the cache once and use that exact data for both the package pins and
    # the dependency metadata stored in the snapshot.
    # TODO: Consider referencing immutable cache release assets instead if they
    # become available through https://github.com/ros/rosdistro/pull/50112.
    cache = load_distribution_cache(args.distro, args.rosdistro_ref)
    distro = Distro(args.distro, distribution_cache=cache)

    if args.package is None:
        deps = distro.get_package_names()
    else:
        deps = distro.get_depends(args.package)
        deps.add(args.package)

    max_len = 0

    if not args.quiet:
        max_len = max(len(dep) for dep in deps)
        print("\033[1m{0:{2}} {1}\033[0m".format("Package", "Version", max_len + 2))

    output = {}

    for dep in sorted(deps):
        try:
            url, tag, _ = distro.get_released_repo(dep)
            version = distro.get_version(dep)
        except AttributeError:
            print(
                "\033[93mPackage '{}' has no version set, skipping...\033[0m".format(
                    dep
                )
            )
            continue

        output[dep] = {
            "url": url,
            "version": version,
            "tag": tag,
            "dependencies": sorted(distro.get_direct_depends(dep)),
        }
        if repository := distro.get_repository_url(dep):
            output[dep]["repository"] = repository

        if not args.quiet:
            print("{0:{2}} {1}".format(dep, version, max_len + 2))

    with open(args.output, "w") as f:
        source = f" at rosdistro {args.rosdistro_ref}" if args.rosdistro_ref else ""
        f.write(
            f"# Snapshot generated by vinca-snapshot on {utc_time} UTC for distro {args.distro}{source}\n"
        )
        yaml.dump(output, f)
