import argparse
import datetime

import yaml
from rosdistro import (
    DistributionCache,
    get_distribution_cache_string,
    get_index,
    get_index_url,
)

from .distro import Distro


def main():
    parser = argparse.ArgumentParser(
        description="Dependency snapshotting tool for ROS packages"
    )
    parser.add_argument(
        "-d",
        "--distro",
        type=str,
        dest="distro",
        default="humble",
        help="ROS distribution to use (default: humble)",
        required=False,
    )
    parser.add_argument(
        "-p",
        "--package",
        type=str,
        dest="package",
        default=None,
        help="ROS package to get dependencies for (default: ALL)",
        required=False,
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        dest="output",
        default="rosdistro_snapshot.yaml",
        help="Output file to write dependencies to",
        required=False,
    )
    parser.add_argument(
        "-q",
        "--quiet",
        dest="quiet",
        action="store_true",
        help="Suppress output to stdout",
        required=False,
    )
    args = parser.parse_args()

    # Get the current UTC time
    utc_time = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    # Fetch the cache once and use that exact data for both the package pins and
    # the dependency metadata stored in the snapshot.
    # TODO: Consider referencing immutable cache release assets instead if they
    # become available through https://github.com/ros/rosdistro/pull/50112.
    index = get_index(get_index_url())
    cache_yaml = get_distribution_cache_string(index, args.distro)
    cache = DistributionCache(args.distro, yaml.safe_load(cache_yaml))
    distro = Distro(args.distro, distribution_cache=cache)

    if args.package is None:
        deps = distro.get_package_names()
    else:
        deps = distro.get_depends(args.package)
        deps.add(args.package)

    if not args.quiet:
        max_len = max([len(dep) for dep in deps])
        print("\033[1m{0:{2}} {1}\033[0m".format("Package", "Version", max_len + 2))

    output = {}

    for dep in sorted(deps):
        try:
            url, tag, _ = distro.get_released_repo(dep)
            version = distro.get_version(dep)
        except AttributeError:
            print(
                "\033[93mPackage '{}' has no version set, skipping...\033[0m".format(
                    dep
                )
            )
            continue

        output[dep] = {
            "url": url,
            "version": version,
            "tag": tag,
            "dependencies": sorted(distro.get_direct_depends(dep)),
        }
        if repository := distro.get_repository_url(dep):
            output[dep]["repository"] = repository

        if not args.quiet:
            print("{0:{2}} {1}".format(dep, version, max_len + 2))

    with open(args.output, "w") as f:
        f.write(
            f"# Snapshot generated by vinca-snapshot on {utc_time} UTC for distro {args.distro}\n"
        )
        yaml.dump(output, f)
