import io
import re
import tarfile
import zipfile
from unittest.mock import patch

import pytest
import ruamel.yaml
import zstandard

from vinca.pinning import (
    PinningError,
    _migration_applies_to_platforms,
    _read_pinning_package,
    dependencies_from_recipes,
    dependencies_from_vinca,
    render_pinning,
    select_completed_migrations,
    update_pinning,
)
from vinca.variant_algebra import variant_add


BASE_CONFIG = b"""\
python:
  - 3.13.* *_cp313
libboost_devel:
  - '1.88'
keep:
  - base
"""

BOOST_MIGRATION = b"""\
__migrator:
  build_number: 1
libboost_devel:
  - '1.90'
migrator_ts: 1234
"""


def _conda_package(files):
    tar_payload = io.BytesIO()
    with tarfile.open(fileobj=tar_payload, mode="w") as archive:
        for name, content in files.items():
            info = tarfile.TarInfo(name)
            info.size = len(content)
            archive.addfile(info, io.BytesIO(content))
    compressed = zstandard.ZstdCompressor().compress(tar_payload.getvalue())
    conda_payload = io.BytesIO()
    with zipfile.ZipFile(conda_payload, mode="w") as archive:
        archive.writestr("metadata.json", '{"conda_pkg_format_version": 2}')
        archive.writestr("pkg-test.tar.zst", compressed)
        archive.writestr("info-test.tar.zst", b"")
    return conda_payload.getvalue()


def test_read_pinning_conda_package():
    payload = _conda_package(
        {
            "conda_build_config.yaml": BASE_CONFIG,
            "share/conda-forge/migrations/libboost190.yaml": BOOST_MIGRATION,
            "ignored.txt": b"not part of the pinning inputs",
        }
    )

    base, migrations = _read_pinning_package(payload)

    assert base == BASE_CONFIG
    assert migrations == {"libboost190": BOOST_MIGRATION}


def test_render_applies_base_migration_then_override(tmp_path):
    config_path = tmp_path / "vinca_pinning.yaml"
    config_path.write_text(
        """\
conda_forge_pinning_version: 2026.01.02.03.04.05
migrations:
  - libboost190
pinning_overrides:
  python:
    - 3.14.* *_cp314
"""
    )
    output_path = tmp_path / "conda_build_config.yaml"

    rendered = render_pinning(
        config_path,
        output_path,
        package=(BASE_CONFIG, {"libboost190": BOOST_MIGRATION}),
    )

    assert rendered["python"] == ["3.14.* *_cp314"]
    assert rendered["libboost_devel"] == ["1.90"]
    assert rendered["keep"] == ["base"]
    assert "__migrator" not in rendered
    assert "migrator_ts" not in rendered
    assert output_path.read_text().startswith(
        "# Generated by vinca-pinning-render from vinca_pinning.yaml."
    )
    assert not any(line.endswith(" ") for line in output_path.read_text().splitlines())


def test_render_keeps_selector_on_empty_sequence_item(tmp_path):
    config_path = tmp_path / "vinca_pinning.yaml"
    config_path.write_text(
        """\
conda_forge_pinning_version: '1'
migrations: []
pinning_overrides: {}
"""
    )
    output_path = tmp_path / "conda_build_config.yaml"
    base = b"""\
target_goexe:
  -                           # [unix]
  - .exe                      # [win]
"""

    render_pinning(config_path, output_path, package=(base, {}))

    output = output_path.read_text()
    assert re.search(r"^  -\s+# \[unix]$", output, re.MULTILINE)
    assert not re.search(r"^\s+# \[unix]$", output, re.MULTILINE)


def test_render_rejects_unknown_migration(tmp_path):
    config_path = tmp_path / "vinca_pinning.yaml"
    config_path.write_text(
        """\
conda_forge_pinning_version: '1'
migrations: [missing]
pinning_overrides: {}
"""
    )

    with pytest.raises(PinningError, match="Migrations not present.*missing"):
        render_pinning(
            config_path,
            tmp_path / "output.yaml",
            package=(BASE_CONFIG, {}),
        )


def test_render_rejects_partial_zipped_override(tmp_path):
    config_path = tmp_path / "vinca_pinning.yaml"
    config_path.write_text(
        """\
conda_forge_pinning_version: '1'
migrations: []
pinning_overrides:
  python: ['3.14']
"""
    )
    base = b"""\
python: ['3.13']
is_python_min: [true]
zip_keys:
  - [python, is_python_min]
"""

    with pytest.raises(PinningError, match="also requires is_python_min"):
        render_pinning(
            config_path,
            tmp_path / "output.yaml",
            package=(base, {}),
        )


def test_cfep9_key_add_updates_zip_group():
    base = {
        "python": ["3.12.*", "3.13.*"],
        "is_python_min": [True, False],
        "zip_keys": [["python", "is_python_min"]],
    }
    migration = {
        "__migrator": {
            "operation": "key_add",
            "primary_key": "python",
            "ordering": {"python": ["3.12.*", "3.13.*", "3.14.*"]},
        },
        "python": ["3.14.*"],
        "is_python_min": [False],
    }

    merged = variant_add(base, migration)

    assert merged["python"] == ["3.12.*", "3.13.*", "3.14.*"]
    assert merged["is_python_min"] == [True, False, False]


def test_cfep9_merges_pin_run_as_build_and_zip_keys():
    merged = variant_add(
        {
            "pin_run_as_build": {"old": {"max_pin": "x"}},
            "zip_keys": [["python", "numpy"]],
        },
        {
            "pin_run_as_build": {"new": {"max_pin": "x.x"}},
            "zip_keys": [["python", "numpy", "is_python_min"]],
        },
    )

    assert merged["pin_run_as_build"] == {
        "old": {"max_pin": "x"},
        "new": {"max_pin": "x.x"},
    }
    assert merged["zip_keys"] == [["is_python_min", "numpy", "python"]]


def test_cfep9_scoped_migration_only_replaces_matching_platform_values():
    yaml = ruamel.yaml.YAML()
    base = yaml.load(
        """\
c_stdlib_version:
  - 2.17  # [linux]
  - 2.28  # [linux and (x86_64 or aarch64)]
  - 11.0  # [osx]
"""
    )
    migration = yaml.load(
        """\
c_stdlib_version:  # [osx]
  - 12.0           # [osx]
"""
    )

    merged = variant_add(base, migration)

    assert merged["c_stdlib_version"] == [2.17, 2.28, 12.0]
    output = io.StringIO()
    yaml.dump(merged, output)
    assert "2.17" in output.getvalue() and "# [linux]" in output.getvalue()
    assert "2.28" in output.getvalue()
    assert "12.0" in output.getvalue() and "# [osx]" in output.getvalue()


def test_dependencies_from_recipes_handles_conditional_requirements(tmp_path):
    recipe_dir = tmp_path / "recipes" / "ros2-example"
    recipe_dir.mkdir(parents=True)
    (recipe_dir / "recipe.yaml").write_text(
        """\
package:
  name: ros2-example
requirements:
  build:
    - ${{ compiler('c') }}
  host:
    - libboost-devel >=1.88
    - if: linux
      then:
        - libcamera
  run:
    - ros2-rclcpp
    - python
"""
    )

    assert dependencies_from_recipes(tmp_path / "recipes") == {
        "libboost-devel",
        "libcamera",
        "python",
    }


def test_dependencies_from_vinca_reuses_distro_and_group_packages(tmp_path):
    distro = type(
        "FakeDistro",
        (),
        {
            "name": "rolling",
            "snapshot": {},
            "additional_packages_snapshot": {},
            "prefetch_additional_package_xml": lambda self: None,
        },
    )()
    config = {
        "ros_distro": "rolling",
        "_snapshot": {},
        "_additional_packages_snapshot": {},
    }
    requirements = iter(
        [
            [{"host": ["python", "ros2-rclcpp"]}],
            [{"host": ["libboost-devel"]}],
            [{"run": ["vtk >=9"]}],
        ]
    )

    with (
        patch("vinca.distro.Distro", return_value=distro) as distro_class,
        patch("vinca.main.read_vinca_yaml", side_effect=lambda path: dict(config)),
        patch(
            "vinca.main.get_group_dependency_packages", return_value=["group-package"]
        ) as get_groups,
        patch("vinca.main.get_selected_packages", return_value=["selected"]),
        patch(
            "vinca.main.generate_dependency_requirements",
            side_effect=lambda distro, config, groups: next(requirements),
        ) as generate_requirements,
    ):
        dependencies = dependencies_from_vinca(tmp_path)

    assert dependencies == {"python", "libboost-devel", "vtk"}
    distro_class.assert_called_once()
    get_groups.assert_called_once_with(distro)
    assert generate_requirements.call_count == 3
    assert all(
        call.args[2] == ["group-package"]
        for call in generate_requirements.call_args_list
    )


def test_selects_only_migrations_done_for_all_relevant_dependencies():
    migrations = {
        "boost": BOOST_MIGRATION,
        "urdfdom": b"urdfdom:\n  - '6'\n",
        "paused": b"__migrator:\n  paused: true\nignored:\n  - 2\n",
    }
    statuses = {
        "boost": {"done": ["pcl"], "in-pr": ["vtk"]},
        "urdfdom": {"done": ["pinocchio"]},
    }

    with (
        patch(
            "vinca.pinning.get_migration_status",
            side_effect=lambda name: statuses[name],
        ),
        patch(
            "vinca.pinning.package_feedstocks",
            side_effect=lambda package: {package},
        ),
    ):
        selected, reports = select_completed_migrations(
            migrations, {"pcl", "vtk", "pinocchio"}
        )

    assert selected == ["urdfdom"]
    assert dict(reports)["boost"].startswith("waiting for vtk")
    assert "paused" not in dict(reports)


def test_migration_platform_selectors_are_respected():
    migration = b"""\
__migrator:
  kind: version
c_stdlib_version:  # [osx]
  - 12.0           # [osx]
"""

    assert _migration_applies_to_platforms(migration, ("osx-64",))
    assert not _migration_applies_to_platforms(migration, ("linux-64",))


def test_existing_active_migration_is_kept_and_overrides_are_unchanged(tmp_path):
    config_path = tmp_path / "vinca_pinning.yaml"
    config_path.write_text(
        """\
conda_forge_pinning_version: old
migrations:
  - boost
pinning_overrides:
  # This comment and value are maintained locally.
  python:
    - 3.14.* *_cp314
"""
    )
    package = (BASE_CONFIG, {"boost": BOOST_MIGRATION})
    pending_status = {"done": [], "in-pr": ["pcl"]}

    with (
        patch("vinca.pinning.download_pinning_package", return_value=package),
        patch("vinca.pinning.get_migration_status", return_value=pending_status),
        patch("vinca.pinning.package_feedstocks", side_effect=lambda name: {name}),
    ):
        version, migrations, _ = update_pinning(
            config_path,
            base_dir=tmp_path,
            dependencies={"pcl"},
            latest_distribution=("new", "https://example.invalid/package.conda"),
        )

    assert version == "new"
    assert migrations == ["boost"]
    text = config_path.read_text()
    assert "This comment and value are maintained locally." in text
    parsed = ruamel.yaml.YAML(typ="safe").load(text)
    assert parsed["pinning_overrides"] == {"python": ["3.14.* *_cp314"]}
