pkg-config:
  conda-forge: [pkg-config]
python-rospkg:
  conda-forge: [rospkg]
python3-rospkg:
  conda-forge: [rospkg]
boost:
  conda-forge: [boost]
python-argparse:
  conda-forge: []
python-catkin-pkg:
  conda-forge: [catkin_pkg]
python3-catkin-pkg:
  conda-forge: [catkin_pkg]
python:
  conda-forge: ['python {{ python }}']
python3:
  conda-forge: ['python {{ python }}']
python3-dev:
  conda-forge: ['python {{ python }}']
python-rosdep:
  conda-forge: [rosdep]
python3-rosdep:
  conda-forge: [rosdep]
python-empy:
  conda-forge: [empy]
python3-empy:
  conda-forge: [empy]
tinyxml:
  conda-forge: [tinyxml]
tinyxml2:
  conda-forge: [tinyxml2]
gtest:
  conda-forge: [gtest]
cmake:
  conda-forge: [cmake]
google-mock:
  conda-forge: [gmock]
python-mock:
  conda-forge: [mock]
python3-mock:
  conda-forge: [mock]
python-nose:
  conda-forge: [nose]
python3-nose:
  conda-forge: [nose]
python-coverage:
  conda-forge: [coverage]
python3-coverage:
  conda-forge: [coverage]
libconsole-bridge-dev:
  conda-forge: [console_bridge]
python-yaml:
  conda-forge: [pyyaml]
python3-yaml:
  conda-forge: [pyyaml]
python3-setuptools:
  conda-forge: [setuptools]
python3-catkin-pkg-modules:
  conda-forge: [catkin_pkg]
python3-rosdep-modules:
  conda-forge: [rosdep]
libboost-system-dev:
  conda-forge: [boost]
libboost-date-time-dev:
  conda-forge: [boost]
libboost-thread-dev:
  conda-forge: [boost]
libpoco-dev:
  conda-forge: [poco]
python-gnupg:
  conda-forge: [python-gnupg]
python-imaging:
  conda-forge: [pillow]
python-crypto:
  conda-forge: [pycrypto]
bzip2:
  conda-forge: [bzip2]
libssl-dev:
  conda-forge: [openssl]
libgpgme-dev:
  conda-forge: []
log4cxx:
  conda-forge: [log4cxx]
apr:
  conda-forge: [apr]
python-netifaces:
  conda-forge: [netifaces]
python3-netifaces:
  conda-forge: [netifaces]
python-paramiko:
  conda-forge: [paramiko]
sbcl:
  conda-forge: []
lz4:
  conda-forge: [lz4]
python-defusedxml:
  conda-forge: [defusedxml]
python-numpy:
  conda-forge: [numpy]
python3-pytest:
  conda-forge: [pytest]
python3-rosdistro-modules:
  conda-forge: [rosdistro]
python3-lark-parser:
  conda-forge: [lark-parser]
cppcheck:
  conda-forge: [cppcheck]
python3-mypy:
  conda-forge: [mypy]
zlib:
  conda-forge: [zlib]
python3-pkg-resources:
  conda-forge: []
python3-cryptography:
  conda-forge: [cryptography]
python3-numpy:
  conda-forge: [numpy]
python3-ifcfg:
  conda-forge: [ifcfg]
python3-flake8:
  conda-forge: [flake8]
python3-pytest-mock:
  conda-forge: [pytest-mock]
yaml:
  conda-forge: [yaml]
asio:
  conda-forge: [asio]
git:
  conda-forge: [git]
spdlog:
  conda-forge: [spdlog]
pcre:
  conda-forge: [pcre]
pydocstyle:
  conda-forge: [pydocstyle]
libxml2-utils:
  conda-forge: [libxml2]
libcunit-dev:
  conda-forge: []
uncrustify:
  conda-forge: [uncrustify]
python3-lxml:
  conda-forge: [lxml]
openssl:
  conda-forge: [openssl]
eigen:
  conda-forge: [eigen]
assimp:
  conda-forge: [assimp]
libqt5-opengl:
  conda-forge: [qt]
libqt5-widgets:
  conda-forge: [qt]
curl:
  conda-forge: [libcurl]
qtbase5-dev:
  conda-forge: [qt]
libqt5-gui:
  conda-forge: [qt]
libqt5-core:
  conda-forge: [qt]
libfreetype6-dev:
  conda-forge: [freetype]
libfreetype6:
  conda-forge: [freetype]
opengl:
  conda-forge: []
libxaw:
  conda-forge: []
libx11-dev:
  conda-forge: []
libxrandr:
  conda-forge: []
libopencv-dev:
  conda-forge: [opencv 3*]
qt5-qmake:
  conda-forge: [qt]
python3-pydot:
  conda-forge: [pydot]
python3-matplotlib:
  conda-forge: [matplotlib]
python3-qt5-bindings:
  conda-forge: [pyqt]
python3-psutil:
  conda-forge: [psutil]
sdl-image:
  conda-forge: [sdl2_image]
graphicsmagick:
  conda-forge: [graphicsmagick]
libboost-program-options:
  conda-forge: [boost]
sdl:
  conda-forge: [sdl2]
libzmq3-dev:
  conda-forge: [zeromq]
libboost-program-options-dev:
  conda-forge: [boost]
